"""Add profile_pic to User and teacher_id to Lesson

Revision ID: 840eb69db66d
Revises: f5c8d1966aa6
Create Date: 2026-01-02 00:47:19.978896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840eb69db66d'
down_revision = 'f5c8d1966aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_lessons_teacher_id_users', 'users', ['teacher_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lessons_teacher_id_users', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###
